---
- hosts: localhost
  vars:
    - opuser: vagrant
  tasks:
    - name: disable iptables
      service: name=iptables state=stopped enabled=no
    - name: install libselinux-python
      yum: name=libselinux-python state=latest
    - name: remove localtime
      file: path=/etc/localtime state=absent
    - name: change timezone
      file: src=/usr/share/zoneinfo/Asia/Tokyo dest=/etc/localtime state=link force=yes mode=0644
    - name: change locale
      lineinfile: >-
        dest=/etc/sysconfig/i18n
        state=present
        regexp=^LANG=
        line='LANG="ja_JP.UTF-8"'
    - name: install remi repository
      command: rpm -Uvh --force http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
    - name: install man
      yum: name=man state=latest
    - name: install apache
      yum: name=httpd state=latest
    - name: start apache and enabled
      service: name=httpd state=started enabled=yes
    - name: create user {{opuser}}
      user: name={{opuser}} uid=1000
    - name: change owner /var/www/html
      file: dest=/var/www/html owner={{opuser}}group={{opuser}}recurse=yes
    - name: create {{opuser}}'s direcotry .ssh
      file: path=/home/{{opuser}}/.ssh state=directory owner={{opuser}} group={{opuser}} mode=0700
    - name: copy authorised_key
      copy: src=/root/.ssh/authorized_keys dest=/home/{{opuser}}/.ssh/authorized_keys owner={{opuser}} group={{opuser}} mode=0400
    - name: grant {{opuser}} to sudo
      lineinfile:
        dest: /etc/sudoers
        backup: yes
        line: "{{opuser}} ALL=(ALL) NOPASSWD:ALL"
    - name: install vim
      yum: name=vim-enhanced state=latest
    - name: copy vimrc for root
      copy: src=vimrc.custom dest=/root/.vimrc backup=yes
    - name: copy vimrc for {{opuser}} 
      copy: src=vimrc.custom dest=/home/{{opuser}}/.vimrc owner={{opuser}} group={{opuser}}  backup=yes
    - name: copy httpd.conf
      copy: src=httpd.conf.custom dest=/etc/httpd/conf/httpd.conf backup=yes
      notify:
        - restart apache
    - name: install gd-last
      yum: name=gd-last enablerepo=remi state=latest
    - name: install php
      yum: name={{item}} enablerepo=remi-php56 state=present
      with_items:
        - php
        - php-common
        - php-pdo
        - php-cli
        - php-devel
        - php-mysqlnd
        - php-mbstring
        - php-gd
        - php-intl
        - php-xml
      notify:
        - restart apache
    - name: copy php.ini.custom
      copy: src=php.ini.custom dest=/etc/php.ini backup=yes
      notify:
        - restart apache

    - name: install mysql repository
      command: rpm -Uvh --force http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm
    - name: install mysql
      yum: name={{item}} state=present
      with_items:
        - mysql
        - mysql-devel
        - mysql-server
        - mysql-utilities
    - name: copy my.conf.custom
      copy: src=my.cnf.custom dest=/etc/my.cnf backup=yes
    - name: start mysql and enabled
      service: name=mysqld state=started enabled=yes
    - name: install ruby dependencies
      yum: name={{item}} enablerepo=remi,epel state=present
      with_items:
        - gcc
        - openssl
        - openssl-devel
        - rpm-build
        - gcc-c++
        - bzip2
        - bzip2-devel
        - libtool
        - zlib
        - zlib-devel
        - httpd-devel
        - openssl-devel
        - curl-devel
        - ncurses-devel
        - gdbm-devel
        - readline
        - readline-devel
        - sqlite
        - sqlite-devel
        - libyaml-devel
        - libffi-devel
        - bison

  handlers:
    - name: restart apache
      service: name=httpd state=restarted
