---
- hosts: localhost
  become: yes
  become_user: makoto
  vars:
    - python_version: 3.5.2
  tasks:
    - name: check pyenv installed
      command: text -x /home/makoto/.pyenv
      register: pyenv_present
      failed_when: pyenv_present.rc not in [0, 2]
    - name: git clone pyenv
      git: repo=https://github.com/yyuu/pyenv.git dest=/home/makoto/.pyenv
      when: pyenv_present.rc == 2

    - name: check pyvirtual installed
      command: text -x /home/makoto/.pyenv/plugins/pyenv-virtualenv
      register: pyvirtual_present
      failed_when: pyvirtual_present.rc no in [0, 2]
    - name: git clone pyenv-virtual
      git: repo=https://github.com/yyuu/pyenv-virtualenv.git dest=/home/makoto/.pyenv/plugins/pyenv-virtualenv
      when: pyvirtual_present.rc == 2


