---
- hosts: localhost
  become: yes
  become_user: makoto
  vars:
    - python_version: 3.5.2
  tasks:
    - name: check pyenv installed
      command: text -x /home/makoto/.pyenv
      register: pyenv_present
      failed_when: pyenv_present.rc not in [0, 2]
    - name: git clone pyenv
      git: repo=https://github.com/yyuu/pyenv.git dest=/home/makoto/.pyenv
      when: pyenv_present.rc == 2

    - name: check pyvirtual installed
      command: text -x /home/makoto/.pyenv/plugins/pyenv-virtualenv
      register: pyvirtual_present
      failed_when: pyvirtual_present.rc not in [0, 2]
    - name: git clone pyenv-virtual
      git: repo=https://github.com/yyuu/pyenv-virtualenv.git dest=/home/makoto/.pyenv/plugins/pyenv-virtualenv
      when: pyvirtual_present.rc == 2

    - name: update pyenv
      command: git pull --rebase chdir=/home/makoto/.pyenv
    - name: update pyenv-virtualenv
      command: git pull --rebase chdir=/home/makoto/.pyenv/plugins/pyenv-virtualenv

    - name: check python installed
      shell: /bin/bash -lc "pyenv versions | grep {{python_version}}"
      register: python_installed
      failed_when: python_installed.rc not in [0, 1]
    - name: install python
      shell: /bin/bash -lc "pyenv install {{python_version}} && pyenv rehash && pyenv global {{python_version}}"
      when: python_installed.rc == 1

